language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest Test
  - python -m pytest Legobot/LegoTests
  - bandit -r .
  - flake8 .
deploy:
  provider: pypi
  user: briggsb
  password:
    secure: e95p+v9HRzAnraAy5LvqT77v0nzFyjAWDOw1twsI1rw77i2trklaXqRpeld1U9OsRqlxDdGc6pqCwu2ZRO/puSOGd5TU4Cr64mnW3IEep57lD5wPFVC9e58ErYU33DZoTZYixH76ftK+ZvSNRYkZbHLeXasyJtC7q87R22cCqjfln1dlTia/D6xU8NVqmf9P8fohTKw6xKHYcKZVT2FHCGLNS/VTu8iHXiRi2KdfZbiuqYwV0JZXWjE+FvjJ3FP1hDIRZtyONz6dDQY9iA9Rs3OoFG1MtMe4nXIRx3F9OWT3Thi01CBTA1NlE326KO+g18KvXYs6yVx1y0evVB5/WXZ/OnqbWckQqjHgMB0l38D3OJJMkQVip/YY+6Xej5+J4u3UyRpli2ggnBm+FcX/waw3FmkBNBv1X8dQ4hQK7aLdNg0SaOK2dYz1lbulaCZH4eevbiwza2rTQNx8qZ6WIArvD6AoNf9/qMnmYfVrLfqhX4NdHWZHjGjNgwdHFsVZwQK270KOGU37dJvRrLXCsiHLi+YScyy3Sr6g+u+H6vowtrcUYzqEh/nFBi8HdZdBLZfd+BNktVNOpGBo7tQAP5hCNTeW6BnbX2lKwEY+t04ONune6FCBPrqKge2mBp0LVQQM60zncSVvhi/lWFXZ4dYEoST0cTLpq1A2r7mftXc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bbriggs/Legobot
    branch: master
notifications:
  slack:
    rooms:
      secure: lpdlVU9JxN84Q4rf8coOk8lLdiRksIGp04FiO8OZ0XjoxmrMIa5tGgTt9X30X93cHDmBIKotVncJUTJkBQX6Qxu5q9t/lEVD04L4sSM0wGlQ7SRzucWH2AVv20pCuW4cAu7gvft0eM7AQqlG6CQdD/hj22n8FnwLnF1SkroZUQLaeej2UyeWt96F4Vcrnq1+S5A4JfaYa9QCzTSQLMEh+ctf2vzNNMw/8tnm77SJOTKswFhj/frM4MQ305djLKU1Y+VEXhvYSQ/HJKsBiIjuEWc5TZ9tpLJE6ZUsbyiazAJ52QreHfkTjQgrBdFRG6lvx/NxTp/JdrJJXNsTaPGtxgZBn7PTrDSGDBl3LzfSy+b687oIPmtj05L2Rk5o18Zzt93DQWbhnszTUn++MtHu1jYV1t3eRJSbj8zSpoKZHo2u9jTCzqyrFJwckTB4SKkySGi9zD02DDPt9leWF9sQyF8t/uj5p/6msktrtXM8Afa1jOKETH5vap4qy7McsQkpdOMRo0fvTVobvMup5QIEqwlpdnyIw4+Q4ShEe4tVz2Ebk42iOgmcfPcFMRiyZz8ApT1WV7AgfwVNfSlAFagFPxPlp+pEP/baFFRhxNANhMesIO7xU355zQ3i3bT386//6CGJumpdsLEXpkUZsWk48MUG6BA9DGNO2B/utz8nGH0=
