language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- python -m pytest Test
- python -m pytest Legobot/LegoTests
- bandit -r .
- flake8 .
notifications:
  irc:
    channels:
      secure: U8Kd6T3g1bDvWEz8yd6AKnyUPlgpi2+5cSE19YpE8Hhn0ufE9Ml/hntR1B37C/YQQ5ec7mQu4LBrRypiAOhV2NJtUD46MamtPuoTPri64H6nNPTRiFDXxLr/w7M4W/VR079VCUHDdBJc1zP2sHGg9OqAOo6FksRohZW6IKbmBWW4/nLEsNEoHeyd3buOTw9xOEtGWFZptmza9JrNKJ+4WeHOMLd3QywYD9po0GKvcfHN4vV8310puwcHVYagx7vIK7eTr+33e++OCOsnS6dtL00ObqbmlqRE3I6vpdkXfT51vcTom1n9z8dJPoKR0n/3yEMr1DcofhvZ05E4k6brCgd/ocn/uMJGu24ZiIwKiyfxJOcGHK8T9+qME8oY95l6MQXXgr7gdPj+1eoWbLQGoxHb9sg7EpUfK7pSHGWGVmj7JFOZv/0DCubqkzoxWyNU5xQWKwWMInEwKfSHCgjGEb1CsFr7Dkpaqp1X9aWqpOu1xiGy/v2G1I8Rsb1wLGWH34GbbRWuIH2PvhDpfX+fc/Jmm5yLDzrT+CPXymKC/EcvSxlfJPVrFTtjh/ZAd/ypTHGUpmSeQg286pKWmri0E9lU/O62eCGBbpyw/Art2QFpLUa8VOnhTRz8nkG5P73BKmKgDsUsPR6GLCH91Q3MQMAPH0TXHNzRXHCP77WvQKo=
deploy:
  provider: pypi
  user: briggsb
  password:
    secure: e95p+v9HRzAnraAy5LvqT77v0nzFyjAWDOw1twsI1rw77i2trklaXqRpeld1U9OsRqlxDdGc6pqCwu2ZRO/puSOGd5TU4Cr64mnW3IEep57lD5wPFVC9e58ErYU33DZoTZYixH76ftK+ZvSNRYkZbHLeXasyJtC7q87R22cCqjfln1dlTia/D6xU8NVqmf9P8fohTKw6xKHYcKZVT2FHCGLNS/VTu8iHXiRi2KdfZbiuqYwV0JZXWjE+FvjJ3FP1hDIRZtyONz6dDQY9iA9Rs3OoFG1MtMe4nXIRx3F9OWT3Thi01CBTA1NlE326KO+g18KvXYs6yVx1y0evVB5/WXZ/OnqbWckQqjHgMB0l38D3OJJMkQVip/YY+6Xej5+J4u3UyRpli2ggnBm+FcX/waw3FmkBNBv1X8dQ4hQK7aLdNg0SaOK2dYz1lbulaCZH4eevbiwza2rTQNx8qZ6WIArvD6AoNf9/qMnmYfVrLfqhX4NdHWZHjGjNgwdHFsVZwQK270KOGU37dJvRrLXCsiHLi+YScyy3Sr6g+u+H6vowtrcUYzqEh/nFBi8HdZdBLZfd+BNktVNOpGBo7tQAP5hCNTeW6BnbX2lKwEY+t04ONune6FCBPrqKge2mBp0LVQQM60zncSVvhi/lWFXZ4dYEoST0cTLpq1A2r7mftXc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bbriggs/Legobot
    branch: master
