language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- python -m pytest Test
- python -m pytest Legobot/LegoTests
deploy:
  provider: pypi
  user: briggsb
  password:
    secure: btmbln/0zwP7geZxfi2oJNCsLHgoQ2Iwl/lPkjN6HBqJJm6MrorPBUUCiD9lSu4UQSAPD0ctGhdJP5GkHzMgmdOum2qMnX15btRSB+FIdoIKNB8THob9ViAlRv4t80f5eS5Yuqief/m1I4nM/2MoJDX0EEP/4ikOgvXavttIzC5SuLVJQoC3vFOV7pG84F7hLOWGXCrkSwnovNV99ReORLbwqoEiiCUkY6PMePv1EuXZybkJpEv1BqIF7+m4AuOgXJqthg1WuDsC1bAacPIPISlfKgme78vLXqFxBBKEER9jlkiLIOGAC9cJtbnqPKPr3uqoTYwnckCx9/geqNh3LFN+Cds5WPb3adQh5f1788miq38MOrGQWciltmMiUGBV5oEeW205pUztBWnWtk9A8x2BbLJi6YybYcG/UQlUru2zhQWQTnxHx0I3SnAbOBoiv7ndF2BMO5vmj4TAlWffRrmB4XALiNkLfpCPg9Jt0exxtnNFjLwA/rXV4AofywyEG7ab92TqPaJs6ygz4BPv41T5uARhbTSeIC1ZfjIMPzyvpQ1XU0508e5WUmuD4az/PWlwF7UENZKsFdBwIQ5iZPe1uZ8pzegJbQ+PzUOc+XNWQmshCdj4CqbHhcGUV77Ksuub0lGdzHVvh7mqc5lriVzHZFtQdc4v4bn2HULsrSY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bbriggs/Legobot
    branch: master
notifications:
  irc:
    channels: 
      secure: U8Kd6T3g1bDvWEz8yd6AKnyUPlgpi2+5cSE19YpE8Hhn0ufE9Ml/hntR1B37C/YQQ5ec7mQu4LBrRypiAOhV2NJtUD46MamtPuoTPri64H6nNPTRiFDXxLr/w7M4W/VR079VCUHDdBJc1zP2sHGg9OqAOo6FksRohZW6IKbmBWW4/nLEsNEoHeyd3buOTw9xOEtGWFZptmza9JrNKJ+4WeHOMLd3QywYD9po0GKvcfHN4vV8310puwcHVYagx7vIK7eTr+33e++OCOsnS6dtL00ObqbmlqRE3I6vpdkXfT51vcTom1n9z8dJPoKR0n/3yEMr1DcofhvZ05E4k6brCgd/ocn/uMJGu24ZiIwKiyfxJOcGHK8T9+qME8oY95l6MQXXgr7gdPj+1eoWbLQGoxHb9sg7EpUfK7pSHGWGVmj7JFOZv/0DCubqkzoxWyNU5xQWKwWMInEwKfSHCgjGEb1CsFr7Dkpaqp1X9aWqpOu1xiGy/v2G1I8Rsb1wLGWH34GbbRWuIH2PvhDpfX+fc/Jmm5yLDzrT+CPXymKC/EcvSxlfJPVrFTtjh/ZAd/ypTHGUpmSeQg286pKWmri0E9lU/O62eCGBbpyw/Art2QFpLUa8VOnhTRz8nkG5P73BKmKgDsUsPR6GLCH91Q3MQMAPH0TXHNzRXHCP77WvQKo=
